version: '3'
services:
  app:
    image: dylancalo/cloud_lab2
    ports:
      - "80:80"
    networks:
      - my-app-net
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      - my-app-net
networks:
  my-app-net:


